const privacyContent = {
    title: "Privacy",
    intro: "This privacy policy explains how Year View handles personal data when you visit the website, try the sample view, sign in, connect a calendar, or use the paid service. Effective date: 08.08.2026.",
    sections: [
        ["Controller and contact", "The controller responsible for this service is Richard Pergens, Stephanstraße 6, 52064 Aachen, Germany. Contact: info@yearview.org. Please use this address for privacy requests and questions."],
        ["Information we process", "We process basic technical information needed to run and protect the service, such as your IP address, browser and device information, the time of a request, and the page or function requested. Clerk handles account and sign-in information for us. When you connect a calendar, Year View processes the calendar information needed to show your requested view. We do not save your calendar dates or event details in our own database or server cache. Uploaded ICS files and preferences may be stored in your browser."],
        ["Purposes and legal bases", "We use your data to provide the website and requested calendar features, manage accounts and subscriptions, and respond to support requests. This is generally based on Art. 6(1)(b) GDPR when it is needed to provide a service you request. Security, abuse prevention, troubleshooting, and service reliability are based on Art. 6(1)(f) GDPR, because we have a legitimate interest in operating a secure and reliable service. We use consent only where consent is legally required, and you may withdraw it at any time."],
        ["Google Calendar data", "If you connect Google Calendar, you give Year View read-only access to the calendars and events needed for the annual view. Year View cannot create, edit, or delete events. Your calendar information is used to provide the requested view and is not saved by Year View. Google remains a separate provider and controller for its own account and API processing. You can revoke access in your Google account or connection settings."],
        ["Local storage and cookies", "Your browser may store preferences and uploaded ICS calendar files on your device so that the service can remember them. Year View does not save these files on its own servers. The sample view uses sample data. Year View does not intentionally use advertising or analytics cookies and does not sell personal information. You can remove browser storage through your browser settings."],
        ["Recipients and service providers", "Cloudflare hosts and delivers the website and service. Clerk provides account, sign-in, and subscription services. Payment providers configured by Clerk process payments and subscription transactions. Google provides the separately authorized calendar service. These providers may process personal data to provide their services and may use their own service providers."],
        ["Retention", "We keep technical request data only as long as needed for security, troubleshooting, and legal requirements. We do not keep your Google Calendar dates or event details in our own database or server cache. Browser storage remains on your device until you remove it or it is removed by your browser. A deletion request may be limited by statutory retention duties."],
        ["International transfers and security", "Connections to the service and Google are encrypted. We use access controls and take reasonable steps to protect information, but no internet service can guarantee absolute security. "],
        ["Required data and automated decisions", "Some technical information is needed to deliver and protect the service. An account is needed for protected features, and a payment method may be needed for a paid subscription. If you do not provide required information, those features may not be available. Year View does not make decisions about you based only on automated processing and does not create profiles about you."],
        ["Your rights and supervisory authority", "Subject to applicable law, you may request access, correction, deletion, restriction of processing, and data portability, and object to processing based on legitimate interests. You may complain to the data protection supervisory authority responsible for your place of residence or the controller's place of establishment. Contact info@yearview.org first; we may need to verify your identity. You can delete local browser data through your browser settings."],
        ["Children and changes", "Year View is not directed to children. We may update this policy when the service or legal requirements change. The current version is published on this page with its effective date: 08.08.2026."]
    ]
};

export default privacyContent;
