const privacyContent = {
    title: "Privacy",
    intro: "This privacy policy explains how Annual View processes personal data when you visit the website, use the demo, sign in, or use the paid calendar service. Effective date: 08.08.2026.",
    sections: [
        ["Controller and contact", "The controller responsible for this service is Richard Pergens, Stephanstraße 6, 52064 Aachen, Germany. Contact: info@yearview.org. Please use this address for privacy requests and questions."],
        ["Information we process", "Depending on how you use the service, we process your name, email address, Google account identifier, authentication and session data, subscription status, Stripe customer and subscription identifiers, billing history, support correspondence, and technical request data such as IP address, browser, device, timestamps, and requested paths. Google Calendar lists and event data are requested only when you connect the integration."],
        ["Purposes and legal bases", "Account creation, authentication, and delivery of the requested calendar service are based on Art. 6(1)(b) GDPR. Subscription administration, payment processing, invoices, fraud prevention, and legally required records are based on Art. 6(1)(b) and Art. 6(1)(c) GDPR. Security, abuse prevention, troubleshooting, and service reliability are based on Art. 6(1)(f) GDPR, with the legitimate interest of operating a secure service. We use consent only where consent is legally required, and you may withdraw it at any time."],
        ["Google Calendar data", "If you connect Google Calendar, Annual View requests the read-only scope https://www.googleapis.com/auth/calendar.readonly and forwards allowlisted calendar-list and event requests to Google. Annual View does not create, edit, or delete events, and calendar responses are returned with no-store caching. Google remains a separate provider and controller for its own account and API processing; this does not replace Annual View's obligations for its own authentication, proxy, and display processing."],
        ["Local storage and cookies", "Supabase authentication persists session data in browser storage. The application may store preferences and imported ICS calendar content in browser storage. The demo uses sample data. Annual View does not intentionally use advertising or analytics cookies and does not sell personal information. You can remove browser storage through your browser settings, although this may sign you out or remove imported calendars."],
        ["Recipients and service providers", "Supabase provides authentication and account infrastructure, Stripe provides checkout and billing, and Cloudflare provides hosting, delivery, and the protected API Worker. These providers may process personal data as processors where they act on the controller's instructions. Their current processing locations, sub-processors, data-processing terms, and transfer safeguards are part of the provider configuration and contracts used for the service. Google acts under its own terms for Google account and Calendar API processing."],
        ["Retention", "Account and subscription records are retained while the account is active and afterwards only for as long as needed for security, dispute handling, accounting, tax, and other statutory retention duties. Support correspondence is retained only as long as needed for the support case and applicable legal claims. Google Calendar event data is not stored in the Annual View database or server cache. A deletion request may be limited by statutory retention duties."],
        ["International transfers and security", "Requests to the service and Google are encrypted in transit. We use access controls and no-store responses for calendar API responses, but no internet service can guarantee absolute security. Where a provider processes data outside the EEA, the transfer relies on the safeguard applicable to that provider and configuration, such as an adequacy decision or EU Standard Contractual Clauses with supplementary measures where required."],
        ["Required data and automated decisions", "Email and authentication data are required to create and secure an account; billing data is required for a paid subscription. If you do not provide required data, the corresponding service cannot be provided. Annual View does not make decisions based solely on automated processing and does not perform profiling."],
        ["Your rights and supervisory authority", "Subject to applicable law, you may request access, correction, deletion, restriction of processing, and data portability, and object to processing based on legitimate interests. You may withdraw consent at any time. You may complain to the data protection supervisory authority responsible for your place of residence or the controller's place of establishment. Contact info@yearview.org first; we may need to verify your identity. You can revoke Google access in your Google account, cancel through Stripe, and delete local browser data through your browser settings."],
        ["Children and changes", "Annual View is not directed to children. We may update this policy when the service or legal requirements change. The current version is published on this page with its effective date: 08.08.2026."]
    ]
};

export default privacyContent;
