const termsContent = {
    title: "Terms",
    intro: "These Terms govern your use of Year View, including the free demo and the paid service. Version effective 08.08.2026.",
    sections: [
        ["Operator and acceptance", "Year View is provided by Richard Pergens, Stephanstraße 6, 52064 Aachen, Germany (\"we\", \"us\", or \"our\"). Before starting a paid subscription, you must actively confirm that you have read and accept these Terms and acknowledge the Privacy Policy. The Terms are available for saving before checkout. Mandatory consumer rights are not waived by these Terms."],
        ["The service", "Year View provides a read-only annual visualization of connected Google Calendar data. The demo uses sample data. We may change, suspend, or discontinue features, including third-party integrations, when reasonably necessary to operate or improve the service."],
        ["Account and Google access", "You must provide accurate account information and keep your sign-in credentials and devices secure. You authorize Year View to request only the Google Calendar permissions you approve. Year View cannot create, edit, or delete events. You are responsible for maintaining your Google Calendar and for revoking access when you no longer want the integration."],
        ["Membership and payment", "The paid service costs the amount shown at checkout, currently 2€ per month or 12€ per year. Stripe processes payments and provides the billing portal. A subscription renews for successive billing periods until canceled. We may change pricing for future periods with reasonable advance notice where required by law."],
        ["Cancellation and withdrawal", "You can cancel through the Stripe Billing Portal at any time. Cancellation normally takes effect at the end of the current paid period, and access remains available until then. Consumers generally have a 14-day withdrawal right for distance contracts unless a statutory exception applies. If you ask us to begin providing the service during the withdrawal period, any required express request, acknowledgement, and proportional payment rules apply. See the Cancellation page for the withdrawal instructions and operational details."],
        ["Acceptable use", "You must not misuse the service, attempt unauthorized access, interfere with its operation, circumvent access controls, use it for unlawful purposes, or submit malicious code. We may suspend access where necessary to protect the service, users, or third parties."],
        ["Your content and open source", "You retain rights in your calendars and imported files. You grant us only the limited permission needed to process connected data and provide the service. The open-source Thunderbird edition is separately licensed as described in the repository; these terms apply to the hosted SaaS service."],
        ["Availability and liability", "The service is provided with reasonable care, but uninterrupted or error-free operation is not promised, particularly where Google, Stripe, Supabase, Cloudflare, or another provider is unavailable. We are liable without limitation for intent, gross negligence, injury to life, body or health, product liability, and other liability that cannot legally be limited. For ordinary negligence, liability for breach of an essential contractual obligation is limited to the foreseeable, typically occurring loss. The statutory rights of consumers and liability for personal data under applicable law remain unaffected."],
        ["Termination and governing law", "You may stop using the service at any time. We may terminate or suspend an account for material breach or where continued operation is not reasonably possible, subject to applicable law and any rights to a refund. German law applies only to the extent that this does not remove mandatory consumer protection. Mandatory consumer jurisdiction rules remain unaffected."],
        ["Contact and changes", "Questions about these terms can be sent to info@yearview.org. We may update these terms by publishing a new version on this page. The version effective on the date of your subscription remains available for reference. Effective date: 08.08.2026."]
    ]
};

export default termsContent;
