const termsContent = {
    title: "Terms",
    intro: "These Terms govern your use of Year View, including the sample view, connected calendar features, and the paid service. Version effective 08.08.2026.",
    sections: [
        ["Operator and acceptance", "Year View is provided by Richard Pergens, Stephanstraße 6, 52064 Aachen, Germany (\"we\", \"us\", or \"our\"). By using Year View, you accept these Terms and acknowledge the Privacy Policy. Mandatory consumer rights are not waived by these Terms."],
        ["The service", "Year View provides a read-only annual view of connected Google Calendar data. The sample view uses sample data, while connected-calendar features require a Clerk account. Calendar dates and event details are used to provide the requested view and are not saved by Year View. Uploaded ICS files and preferences may be stored in your browser on your device. Paid subscriptions and their customer-facing billing controls are provided through Clerk Billing. We may change, suspend, or discontinue features, including third-party integrations, when reasonably necessary to operate or improve the service."],
        ["Account and Google access", "You must provide accurate account information and keep your sign-in credentials and devices secure. Clerk manages sign-in and account access. You authorize Year View to request only the Google Calendar permissions you approve. Year View cannot create, edit, or delete events. You are responsible for maintaining your Google Calendar and for revoking access when you no longer want the integration."],
        ["Subscriptions and billing", "Subscription prices, billing intervals, renewal, cancellation, payment methods, and applicable taxes are shown through Clerk Billing before purchase and in your account controls. Your subscription is managed through the billing provider configured for the service. Statutory consumer cancellation, withdrawal, refund, and warranty rights remain unaffected."],
        ["Sample view", "The sample view is available without an account and uses sample data. It does not provide access to another person's calendar. To use your own connected calendar, you must sign in and grant the requested read-only access."],
        ["Acceptable use", "You must not misuse the service, attempt unauthorized access, interfere with its operation, circumvent access controls, use it for unlawful purposes, or submit malicious code. We may suspend access where necessary to protect the service, users, or third parties."],
        ["Your content and open source", "You retain rights in your calendars and imported files. You grant us only the limited permission needed to process connected data and provide the service. Calendar dates and event details are not saved by Year View. Imported ICS files may remain in your browser on your device until you remove them. The open-source Thunderbird edition is separately licensed as described in the repository; these Terms apply to the hosted SaaS service."],
        ["Availability and liability", "The service is provided with reasonable care, but uninterrupted or error-free operation is not promised, particularly where Cloudflare or another provider is unavailable. We are liable without limitation for intent, gross negligence, injury to life, body or health, product liability, and other liability that cannot legally be limited. For ordinary negligence, liability for breach of an essential contractual obligation is limited to the foreseeable, typically occurring loss. The statutory rights of consumers and liability for personal data under applicable law remain unaffected."],
        ["Termination and governing law", "You may stop using the service at any time. We may terminate or suspend an account for material breach or where continued operation is not reasonably possible, subject to applicable law and any rights to a refund. German law applies only to the extent that this does not remove mandatory consumer protection. Mandatory consumer jurisdiction rules remain unaffected."],
        ["Contact and changes", "Questions about these terms can be sent to info@yearview.org. We may update these terms by publishing a new version on this page. Effective date: 08.08.2026."]
    ]
};

export default termsContent;
